version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test --trace --cover
      - store_test_results:
          path: /tmp/junit-reports
      # - store_artifacts:
      #     path: /tmp/excoveralls
